#! /bin/bash

## date:    2021.05.31
## file:    compile and install cmake
## author:  duruyao@hikvision.com
## release: https://cmake.org/download/

if [ $# != 2 ]; then
  printf "USAGE (sudo permission may be needed):\n"
	printf "    %s <TAR_GZ_DIR> <INSTALL_DIR>\n" "${0}"
	exit 1;
fi

zip_dir="${1}"
ins_dir="${2}"
new_folder="$(dirname "${zip_dir}")/cmake_source"

mkdir -p "${new_folder}" && rm -rf "${new_folder:?}/"*
tar -xf "${zip_dir}" -C "${new_folder}"

src_dir="${new_folder}/$(ls "${new_folder}")"

mkdir -p "${ins_dir}" && rm -rf "${ins_dir:?}/"*
cd "${src_dir}" || exit

./bootstrap --prefix="${ins_dir}"
make -j16 && make install

printf "\n"
printf "Install cmake "
printf "to \`${ins_dir}\`:\n"
ls -all "${ins_dir}"
printf "\n"
