#! /bin/bash

## date:	2021.05.17
## file:	compile and install re2
## author:	duruyao@hikvision.com
## release: https://github.com/google/re2/releases

if [ $# != 2 ]; then
  printf "USAGE (sudo permission may be needed):\n"
	printf "	\`${0} <ZIP_DIR> <INSTALL_DIR>\`\n"
	exit 1;
fi

zip_dir="${1}"
ins_dir="${2}"
new_folder="`dirname ${zip_dir}`/re2_source"

mkdir -p ${new_folder} && rm -rf ${new_folder}/*
unzip -q ${zip_dir} -d ${new_folder}

src_dir="${new_folder}/`ls ${new_folder}`"
makefile_dir="${src_dir}/MakeFile"
old_ins_dir="/usr/local"

mkdir -p ${ins_dir} && rm -rf ${ins_dir}/*
cd ${src_dir}

## modify `prefix="/usr/local"` in `Makefile`
ins_dir=${ins_dir//\//\\\/}
ins_dir_old="/usr/local"
ins_dir_old=${ins_dir_old//\//\\\/}

sed -i "s/prefix=${ins_dir_old}/prefix=${ins_dir}/g" `grep "prefix=${ins_dir_old}" -rl Makefile`

make -j16 && make install

printf "\n"
printf "Install re2 "
printf "to \`${ins_dir}\`:\n"
ls -all ${ins_dir}
printf "\n"

