#! /bin/bash

## date:	2021.05.17
## file:	compile and install zlib
## author:	duruyao@hikvision.com
## release: https://www.zlib.net/

if [ $# != 2 ]; then
  printf "USAGE (sudo permission may be needed):\n"
	printf "	\`${0} <ZIP_DIR> <INSTALL_DIR>\`\n"
	exit 1;
fi

zip_dir="${1}"
ins_dir="${2}"
new_folder="`dirname ${zip_dir}`/zlib_source"

mkdir -p ${new_folder} && rm -rf ${new_folder}/*
unzip -q ${zip_dir} -d ${new_folder}

src_dir="${new_folder}/`ls ${new_folder}`"

mkdir -p ${ins_dir} && rm -rf ${ins_dir}/*
cd ${src_dir}

./configure --prefix=${ins_dir}

make -j16 && make install

printf "\n"
printf "Install zlib "
printf "to \`${ins_dir}\`:\n"
ls -all ${ins_dir}
printf "\n"

