################################################################################
#       USING GRPC                                                             #
################################################################################

if (NOT DEFINED USE_GRPC_CMAKE)
    set(USE_GRPC_CMAKE)

    include(${PROJECT_SOURCE_DIR}/tools/cmake/use_hiksdk.cmake)
    include(${PROJECT_SOURCE_DIR}/tools/cmake/use_absl.cmake)

    if (WIN32)
        ## TODO: set grpc_home
        ##
    elseif (UNIX AND NOT APPLE)
        set(grpc_home ${HIKSDK_DIR}/grpc)
        set(grpc_bin_dir ${grpc_home}/bin)
        set(grpc_lib_dir ${grpc_home}/lib)
        set(grpc_include_dir ${grpc_home}/include)

        list(APPEND CMAKE_PREFIX_PATH ${grpc_home}/cmake)
        list(APPEND CMAKE_PREFIX_PATH ${grpc_home}/lib/cmake)

        link_directories(${grpc_lib_dir})
        include_directories(SYSTEM ${grpc_include_dir})
        include_directories(${grpc_out_dir})
    else (APPLE)
        ## TODO: set grpc_home
        ##
    endif ()

    #set(grpc_in_dir ${CMAKE_CURRENT_SOURCE_DIR}/proto)

    if (DEFINED grpc_in_dir AND DEFINED grpc_out_dir)
        ## make dir for `*.grpc.pb.cc`, `*.grpc.pb.h` files generated by `protoc`
        file(MAKE_DIRECTORY ${grpc_out_dir})

        ## get all `*.proto` files
        file(GLOB grpc_all_files CONFIGURE_DEPENDS "${grpc_in_dir}/*.proto")
        list(APPEND grpc_files ${grpc_all_files})

        add_custom_command(OUTPUT grpc_gen_files
                COMMAND export LD_LIBRARY_PATH=${LD_LIBRARY_PAT}:${proto_lib_dir}:${grpc_lib_dir} && ${proto_bin_dir}/protoc -I ${grpc_in_dir} --grpc_out=${grpc_out_dir} --plugin=protoc-gen-grpc=${grpc_bin_dir}/grpc_cpp_plugin ${proto_files}
                DEPENDS ${grpc_files}
                )

        add_custom_target(grpc_2_cxx DEPENDS grpc_gen_files)
    else ()
        message(ERROR "include 'use_grpc.cmake' without defining 'grpc_in_dir' or 'grpc_out_dir'")
    endif ()

    list(APPEND third_party_libs grpc++_reflection grpc++ pthread)

endif (NOT DEFINED USE_GRPC_CMAKE)